name: Segre Regressions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  regressions:
    name: Test Arithmetic Operations
    runs-on: ubuntu-latest
    container: lukasgrau/modelsim_centos:latest
    steps:
      - name: Segre regressions
        run: |
          echo "Running arithmetic tests"
          vsim -c -do "do scripts/tcl/compile.tcl add"
          #./CI/scripts/arith_regressions.sh
