name: Segre Regressions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  regressions:
    name: Test Arithmetic Operations
    runs-on: ubuntu-latest
    container: docker:/batholemew/modelsim:2019.1
    steps:
      - name: Segre regressions
        run: |
          echo "Running arithmetic tests"
          ./CI/scripts/arith_regressions.sh
