name: Segre Regressions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  regressions:
    name: Test Arithmetic Operations
    runs-on: ubuntu-latest
    container: 
      image: lukasgrau/modelsim_centos:latest
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Segre regressions
        run: |
          echo "Running arithmetic tests"
          pwd
          ls -la
          #vsim -c -do "do scripts/tcl/compile.tcl add"
          ./CI/scripts/arith_regressions.sh
